### ISSUE TITLE
채널등록 동작하지 않음: "...옵이 없습니다."

### ISSUE THREAD

**Issue by changwoo** [devunt/ika#11]
옵이 있는 상황에서도 "채널등록 #channelname" 명령에 대해

"해당 채널 #channelname 에 username 유저에 대한 옵이 없습니다."

메시지가 나오면서 동작하지 않습니다.

**Comment by changwoo** [comment]
현재 상황:

"채널등록 명령을 처리하는 도중 문제가 발생했습니다. 잠시 후 다시 한번 시도해주세요. 문제가 계속된다면 #ozinger 에 말씀해주세요."

**Comment by devunt** [comment]
5ff49530eaa7 에서 문제 일부 수정되었습니다. 아직 옵이 없다고 인식되는 문제는 수정되지 않았으나, 채널 등록 명령을 처리하는 도중 문제가 발생한다고 나오는 내용은 더 이상 발생하지 않습니다.

**Comment by devunt** [comment]
v0.2에서 해결되었습니다.
