### ISSUE TITLE
Channel close 기능

### ISSUE THREAD

**Issue by revi** [devunt/ika#12]
Atheme 시절엔 그런 기능이 있었던 것 같기도 하고 실제로 쓰는 걸 본 적도 있는 것 같은데 ika엔 구현이 안 된 건지 Oper-only인지는 모르겠네요. 일단 `/commands/` 폴더들에 `close_channel` 따위의 것은 없길래 올려 봅니다.

**Comment by devunt** [comment]
구현되었습니다.
