### ISSUE TITLE
오징어덮밥 봇문제

### ISSUE THREAD

**Issue by Naekkori** [devunt/ika#3]
Vhost 기능을 사용하기 위해서 오징어 봇을 로그인 하였습니다.
도메인 을 연결하기위하여  REQUEST 명령을 보냈으나, 적용은 안되고 "먼저 로그인 하셔야 합니다." 라는 메세지만 계속 나오는겁니다.

어서 이문제를 해결해주시면 감사하겠습니다.
-Korean12-

**Comment by devunt** [comment]
해당 기능 현재 비활성화되어 있으며 앞으로 구현할 예정에 있습니다.

**Comment by devunt** [comment]
구현되었습니다.
