### ISSUE TITLE
도움말 문제

### ISSUE THREAD

**Issue by ghost** [devunt/ika#6]
> _<이 채널 관리 봇도 겸한다고 해서 새 명령어를 확인하기 위해 /msg >_< help를 사용했더니 오징어 계정 관련 명령은 있는데 채널 관련 명령어는 없더군요.
> 혹시나 해서 /msg ㅇㅈㅇ help를 사용했더니 역시 채널 관련 명령어는 없었고요.
> 채널 명령이 아직 준비되지 않은 건가요?

**Comment by devunt** [comment]
네 아직 구현되지 않았으며 빠른 시일 이내로 구현이 될 예정입니다. 죄송합니다.

**Comment by devunt** [comment]
채널 관련 명령은 일부 준비되었습니다.
