### ISSUE TITLE
채널에서 채널 주인이 q를 지정해서 주질 못합니다.

### ISSUE THREAD

**Issue by readingsnail** [devunt/ika#7]
ㅇㅈㅇ때는 +qo가 정상적으로 되었는데, >_<에 와서는 +o만 됩니다. 나중에 고치실때 추가 부탁드립니다 :)

**Comment by Intrainos** [comment]
추가: 기존 ㅇㅈㅇ에서 q옵션이 여려 사용자에게 있을때 발생하는 문제입니다.

**Comment by devunt** [comment]
상황이 이해가 잘 안 되는데 조금 더 구체적으로 설명해주실 수 있으신가요? 추가적으로 문제가 발생하는 채널명과 유저명 등을 알려주시면
감사하겠습니다.

**Comment by Intrainos** [comment]
#uncyclopedia 에서 발생하는 문제입니다.

**Comment by Intrainos** [comment]
유저명은 책읽는달팽 계정, Luftschloss 계정 입니다. 기존 ㅇㅈㅇ에서 Flags로 +qo를 사용하였습니다. 채널 주인은 정상적으로 작동하는것으로 보아, Flags로 여려 사용자에게 사용하도록 하면 +q가 되지 않는것 같습니다.

**Comment by Intrainos** [comment]
현제 확인 안된계정으로는 Lemin어쩌구 님 계정입니자.

**Comment by devunt** [comment]
아마도 해결되었습니다.
