### ISSUE TITLE
>_<가 안들어오는 문제.

### ISSUE THREAD

**Issue by Intrainos** [devunt/ika#8]
ㅇㅈㅇ의 경우, 채널에 아무도 없거나, 활동이 매우 없으면(이부분은 저도 잘 모르겠습니다.) 자동으로 나가진 후, 다른사람이 Join을 하면 다시 같이 들어옵니다. 하지만, 나간 후로 방치된 후. >_<로 교체되면서, Join시 들어오지 않습니다. 채널 정보를 조회하면, 개설일만 나옵니다. 하지만 이것으로 개설된 채널이란 것을 알 수 있습니다. 해결 부탁드립니다.

**Comment by devunt** [comment]
이미 알고 있는 문제이며 고쳐질 예정입니다. 단, 채널에 조인해있지 않더라도 자동 권한 부여 등의 기능은 제대로 작동하니 일단 급한
문제는 아닌 것 같네요.

**Comment by devunt** [comment]
수정되었습니다.
